default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>



development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: cook_daddy_development

test:
  <<: *default
  adapter: mysql2
  database: cook_daddy_test
  username: root
  password:
  host: localhost
  database: cook_daddy_test


production:
  <<: *default
  database: cook_daddy_production
  username: cook_daddy
  password: <%= ENV['COOK_DADDY_DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
